# This file has been autogenerated by the pywayland scanner

# Copyright © 2022 Vaxry
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from __future__ import annotations

import enum

from pywayland.protocol_core import Argument, ArgumentType, Global, Interface, Proxy, Resource

from .wayland import WlBuffer
from .wayland import WlBufferProxy
from .wlr_foreign_toplevel_management_unstable_v1 import ZwlrForeignToplevelHandleV1
from .wlr_foreign_toplevel_management_unstable_v1 import ZwlrForeignToplevelHandleV1Proxy


class HyprlandToplevelExportFrameV1(Interface):
    """A frame ready for copy

    This object represents a single frame.

    When created, a series of buffer events will be sent, each representing a
    supported buffer type. The "buffer_done" event is sent afterwards to
    indicate that all supported buffer types have been enumerated. The client
    will then be able to send a "copy" request. If the capture is successful,
    the compositor will send a "flags" followed by a "ready" event.

    :class:`~pywayland.protocol.wayland.WlShm` buffers are always supported,
    ie. the "buffer" event is guaranteed to be sent.

    If the capture failed, the "failed" event is sent. This can happen anytime
    before the "ready" event.

    Once either a "ready" or a "failed" event is received, the client should
    destroy the frame.
    """

    name = "hyprland_toplevel_export_frame_v1"
    version = 2

    class error(enum.IntEnum):
        already_used = 0
        invalid_buffer = 1

    class flags(enum.IntFlag):
        y_invert = 1


class HyprlandToplevelExportManagerV1(Interface):
    """Manager to inform clients and begin capturing

    This object is a manager which offers requests to start capturing from a
    source.
    """

    name = "hyprland_toplevel_export_manager_v1"
    version = 2


class HyprlandToplevelExportFrameV1Resource(Resource[HyprlandToplevelExportFrameV1]):
    interface = HyprlandToplevelExportFrameV1

    @HyprlandToplevelExportFrameV1.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
    )
    def buffer(self, format: int, width: int, height: int, stride: int) -> None:
        """Wl_shm buffer information

        Provides information about :class:`~pywayland.protocol.wayland.WlShm`
        buffer parameters that need to be used for this frame. This event is
        sent once after the frame is created if
        :class:`~pywayland.protocol.wayland.WlShm` buffers are supported.

        :param format:
            buffer format
        :type format:
            `ArgumentType.Uint`
        :param width:
            buffer width
        :type width:
            `ArgumentType.Uint`
        :param height:
            buffer height
        :type height:
            `ArgumentType.Uint`
        :param stride:
            buffer stride
        :type stride:
            `ArgumentType.Uint`
        """
        self._post_event(0, format, width, height, stride)

    @HyprlandToplevelExportFrameV1.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
    )
    def damage(self, x: int, y: int, width: int, height: int) -> None:
        """Carries the coordinates of the damaged region

        This event is sent right before the ready event when ignore_damage was
        not set. It may be generated multiple times for each copy request.

        The arguments describe a box around an area that has changed since the
        last copy request that was derived from the current screencopy manager
        instance.

        The union of all regions received between the call to copy and a ready
        event is the total damage since the prior ready event.

        :param x:
            damaged x coordinates
        :type x:
            `ArgumentType.Uint`
        :param y:
            damaged y coordinates
        :type y:
            `ArgumentType.Uint`
        :param width:
            current width
        :type width:
            `ArgumentType.Uint`
        :param height:
            current height
        :type height:
            `ArgumentType.Uint`
        """
        self._post_event(1, x, y, width, height)

    @HyprlandToplevelExportFrameV1.event(
        Argument(ArgumentType.Uint),
    )
    def flags(self, flags: int) -> None:
        """Frame flags

        Provides flags about the frame. This event is sent once before the
        "ready" event.

        :param flags:
            frame flags
        :type flags:
            `ArgumentType.Uint`
        """
        self._post_event(2, flags)

    @HyprlandToplevelExportFrameV1.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
    )
    def ready(self, tv_sec_hi: int, tv_sec_lo: int, tv_nsec: int) -> None:
        """Indicates frame is available for reading

        Called as soon as the frame is copied, indicating it is available for
        reading. This event includes the time at which presentation happened
        at.

        The timestamp is expressed as tv_sec_hi, tv_sec_lo, tv_nsec triples,
        each component being an unsigned 32-bit value. Whole seconds are in
        tv_sec which is a 64-bit value combined from tv_sec_hi and tv_sec_lo,
        and the additional fractional part in tv_nsec as nanoseconds. Hence,
        for valid timestamps tv_nsec must be in [0, 999999999]. The seconds
        part may have an arbitrary offset at start.

        After receiving this event, the client should destroy the object.

        :param tv_sec_hi:
            high 32 bits of the seconds part of the timestamp
        :type tv_sec_hi:
            `ArgumentType.Uint`
        :param tv_sec_lo:
            low 32 bits of the seconds part of the timestamp
        :type tv_sec_lo:
            `ArgumentType.Uint`
        :param tv_nsec:
            nanoseconds part of the timestamp
        :type tv_nsec:
            `ArgumentType.Uint`
        """
        self._post_event(3, tv_sec_hi, tv_sec_lo, tv_nsec)

    @HyprlandToplevelExportFrameV1.event()
    def failed(self) -> None:
        """Frame copy failed

        This event indicates that the attempted frame copy has failed.

        After receiving this event, the client should destroy the object.
        """
        self._post_event(4)

    @HyprlandToplevelExportFrameV1.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
    )
    def linux_dmabuf(self, format: int, width: int, height: int) -> None:
        """Linux-dmabuf buffer information

        Provides information about linux-dmabuf buffer parameters that need to
        be used for this frame. This event is sent once after the frame is
        created if linux-dmabuf buffers are supported.

        :param format:
            fourcc pixel format
        :type format:
            `ArgumentType.Uint`
        :param width:
            buffer width
        :type width:
            `ArgumentType.Uint`
        :param height:
            buffer height
        :type height:
            `ArgumentType.Uint`
        """
        self._post_event(5, format, width, height)

    @HyprlandToplevelExportFrameV1.event()
    def buffer_done(self) -> None:
        """All buffer types reported

        This event is sent once after all buffer events have been sent.

        The client should proceed to create a buffer of one of the supported
        types, and send a "copy" request.
        """
        self._post_event(6)


class HyprlandToplevelExportManagerV1Resource(Resource[HyprlandToplevelExportManagerV1]):
    interface = HyprlandToplevelExportManagerV1


class HyprlandToplevelExportFrameV1Proxy(Proxy[HyprlandToplevelExportFrameV1]):
    interface = HyprlandToplevelExportFrameV1

    @HyprlandToplevelExportFrameV1.request(
        Argument(ArgumentType.Object, interface=WlBuffer),
        Argument(ArgumentType.Int),
    )
    def copy(self, buffer: WlBufferProxy, ignore_damage: int) -> None:
        """Copy the frame

        Copy the frame to the supplied buffer. The buffer must have the correct
        size, see :func:`HyprlandToplevelExportFrameV1.buffer()` and
        :func:`HyprlandToplevelExportFrameV1.linux_dmabuf()`. The buffer needs
        to have a supported format.

        If the frame is successfully copied, a "flags" and a "ready" event is
        sent. Otherwise, a "failed" event is sent.

        This event will wait for appropriate damage to be copied, unless the
        ignore_damage arg is set to a non-zero value.

        :param buffer:
        :type buffer:
            :class:`~pywayland.protocol.wayland.WlBuffer`
        :param ignore_damage:
        :type ignore_damage:
            `ArgumentType.Int`
        """
        self._marshal(0, buffer, ignore_damage)

    @HyprlandToplevelExportFrameV1.request()
    def destroy(self) -> None:
        """Delete this object, used or not

        Destroys the frame. This request can be sent at any time by the client.
        """
        self._marshal(1)
        self._destroy()


class HyprlandToplevelExportManagerV1Proxy(Proxy[HyprlandToplevelExportManagerV1]):
    interface = HyprlandToplevelExportManagerV1

    @HyprlandToplevelExportManagerV1.request(
        Argument(ArgumentType.NewId, interface=HyprlandToplevelExportFrameV1),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Uint),
    )
    def capture_toplevel(self, overlay_cursor: int, handle: int) -> HyprlandToplevelExportFrameV1Proxy:
        """Capture a toplevel

        Capture the next frame of a toplevel. (window)

        The captured frame will not contain any server-side decorations and
        will ignore the compositor-set geometry, like e.g. rounded corners.

        It will contain all the subsurfaces and popups, however the latter will
        be clipped to the geometry of the base surface.

        The handle parameter refers to the address of the window as seen in
        `hyprctl clients`. For example, for d161e7b0 it would be 3512854448.

        :param overlay_cursor:
            composite cursor onto the frame
        :type overlay_cursor:
            `ArgumentType.Int`
        :param handle:
            the handle of the toplevel (window) to be captured
        :type handle:
            `ArgumentType.Uint`
        :returns:
            :class:`~pywayland.protocol.hyprland_toplevel_export_v1.HyprlandToplevelExportFrameV1`
        """
        frame = self._marshal_constructor(0, HyprlandToplevelExportFrameV1, overlay_cursor, handle)
        return frame

    @HyprlandToplevelExportManagerV1.request()
    def destroy(self) -> None:
        """Destroy the manager

        All objects created by the manager will still remain valid, until their
        appropriate destroy request has been called.
        """
        self._marshal(1)
        self._destroy()

    @HyprlandToplevelExportManagerV1.request(
        Argument(ArgumentType.NewId, interface=HyprlandToplevelExportFrameV1),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Object, interface=ZwlrForeignToplevelHandleV1),
        version=2,
    )
    def capture_toplevel_with_wlr_toplevel_handle(self, overlay_cursor: int, handle: ZwlrForeignToplevelHandleV1Proxy) -> HyprlandToplevelExportFrameV1Proxy:
        """Capture a toplevel

        Same as capture_toplevel, but with a
        :class:`~pywayland.protocol.wlr_foreign_toplevel_management_unstable_v1.ZwlrForeignToplevelHandleV1`
        handle.

        :param overlay_cursor:
            composite cursor onto the frame
        :type overlay_cursor:
            `ArgumentType.Int`
        :param handle:
            the
            :class:`~pywayland.protocol.wlr_foreign_toplevel_management_unstable_v1.ZwlrForeignToplevelHandleV1`
            handle of the toplevel to be captured
        :type handle:
            :class:`~pywayland.protocol.wlr_foreign_toplevel_management_unstable_v1.ZwlrForeignToplevelHandleV1`
        :returns:
            :class:`~pywayland.protocol.hyprland_toplevel_export_v1.HyprlandToplevelExportFrameV1`
        """
        frame = self._marshal_constructor(2, HyprlandToplevelExportFrameV1, overlay_cursor, handle)
        return frame


class HyprlandToplevelExportFrameV1Global(Global[HyprlandToplevelExportFrameV1]):
    interface = HyprlandToplevelExportFrameV1


class HyprlandToplevelExportManagerV1Global(Global[HyprlandToplevelExportManagerV1]):
    interface = HyprlandToplevelExportManagerV1


HyprlandToplevelExportFrameV1._gen_c()
HyprlandToplevelExportFrameV1.proxy_class = HyprlandToplevelExportFrameV1Proxy
HyprlandToplevelExportFrameV1.resource_class = HyprlandToplevelExportFrameV1Resource
HyprlandToplevelExportFrameV1.global_class = HyprlandToplevelExportFrameV1Global


HyprlandToplevelExportManagerV1._gen_c()
HyprlandToplevelExportManagerV1.proxy_class = HyprlandToplevelExportManagerV1Proxy
HyprlandToplevelExportManagerV1.resource_class = HyprlandToplevelExportManagerV1Resource
HyprlandToplevelExportManagerV1.global_class = HyprlandToplevelExportManagerV1Global
