cmake_minimum_required(VERSION 3.19)
project(nsproxy CXX)
set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(PkgConfig REQUIRED)
pkg_check_modules(HL REQUIRED IMPORTED_TARGET hyprland pixman-1 libdrm glesv2)
add_library(nsproxy SHARED src/main.cpp)
target_link_libraries(nsproxy PRIVATE PkgConfig::HL)
target_compile_options(nsproxy PRIVATE -fno-gnu-unique -Wall)
