#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Assemble the FSR 1.0 EASU / RCAS GLSL ES fragment shaders from AMD's headers (MIT, see LICENSE-AMD-FSR.txt)
into fsr_shaders.h as C string literals. Run after touching this file; the headers are used verbatim."""
import os
here = os.path.dirname(os.path.abspath(__file__))
rd = lambda n: open(os.path.join(here, n)).read()

PRE = """#version 310 es
precision highp float;
precision highp int;
#define A_GPU 1
#define A_GLSL 1
"""
A = rd("ffx_a.h")
FSR = rd("ffx_fsr1.h")
# strict GLSL compilers (Mesa) reject int->uint assignments that AMD's header relies on
FSR = FSR.replace("con3[2]=con3[3]=0;", "con3[2]=con3[3]=0u;").replace("con[2]=0;", "con[2]=0u;").replace("con[3]=0;", "con[3]=0u;")

EASU = PRE + A + """
#define FSR_EASU_F 1
uniform sampler2D srcTex;
uniform uvec4 con0, con1, con2, con3;
AF4 FsrEasuRF(AF2 p) { return AF4(textureGather(srcTex, p, 0)); }
AF4 FsrEasuGF(AF2 p) { return AF4(textureGather(srcTex, p, 1)); }
AF4 FsrEasuBF(AF2 p) { return AF4(textureGather(srcTex, p, 2)); }
""" + FSR + """
out vec4 fragColor;
void main() {
  AU2 ip = AU2(gl_FragCoord.xy);
  AF3 c;
  FsrEasuF(c, ip, con0, con1, con2, con3);
  fragColor = vec4(c, 1.0);
}
"""

RCAS = PRE + A + """
#define FSR_RCAS_F 1
uniform sampler2D srcTex;
uniform uvec4 con;
AF4 FsrRcasLoadF(ASU2 p) { return AF4(texelFetch(srcTex, ivec2(p), 0)); }
void FsrRcasInputF(inout AF1 r, inout AF1 g, inout AF1 b) {}
""" + FSR + """
out vec4 fragColor;
void main() {
  AU2 ip = AU2(gl_FragCoord.xy);
  AF3 c;
  FsrRcasF(c.r, c.g, c.b, ip, con);
  fragColor = vec4(c, 1.0);
}
"""

def lit(name, src):
    lines = src.split("\n")
    body = "\n".join('    "' + l.replace("\\", "\\\\").replace('"', '\\"') + '\\n"' for l in lines)
    return "static const char *%s =\n%s;\n" % (name, body)

open(os.path.join(here, "fsr_shaders.h"), "w").write(
    "/* generated by gen_shaders.py - do not edit */\n" + lit("FS_EASU", EASU) + "\n" + lit("FS_RCAS", RCAS))
print("ok", len(EASU), len(RCAS))
